

export enum RoleEnum {
    SUPER_ADMINISTRATOR = "SUPER_ADMINISTRATOR",
    ADMINISTRATOR = "ADMINISTRATOR",
    COURT_MANAGER = "COURT_MANAGER",
    CLEANING_STAFF = "CLEANING_STAFF",
    RECEPTIONIST = "RECEPTIONIST",
}